services: docker
language: node_js
node_js:
  - "8"

cache: npm

stages:
  # - test
  - name: build
    if: branch = master

jobs:
  include:
    # - stage: test
    #   install: npm install
    #   script: npm test
    - stage: build
      script:
        - npm install
        - npm run clean
        - echo "{\"version\": \"sprint_0.XX.Y\",\"commit_id\":\"`git ls-remote https://github.com/KNMI/GeoWeb-FrontEnd.git rev-parse HEAD | awk '{print $1}'`\" }" > ./config/config.json
        - npm run deploy:prod-quick
