services: docker
language: node_js
node_js:
  - "8"

cache: npm

stages:
  # - test
  - name: build
    if: branch = master

jobs:
  include:
    # - stage: test
    #   install: npm install
    #   script: npm test
    - stage: build
      script:
        - npm install
        - npm run clean
        - ls -la
        - "echo {\"version\": \"sprint_0.XX.Y\",\"commit_id\":\"$TRAVIS_COMMIT\" } > config/config.json"
        - npm run deploy:prod-quick
        - ls -la
